
server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio
    username: joshua
    password:
  jpa:
    hibernate:
      ddl-auto: validate    # never auto-modify the schema
    show-sql: true          # logs SQL queries ? turn off in prod
  flyway:
    enabled: true
    locations: classpath:db/migration